development:
  :concurrency: 5
  max_retries: 0
production:
  :concurrency: 20
:queues:
  - default

:schedule:
  get_tickers:
    in: 1y
    class: GetTickersJob
    enabled: false

  get_ticker_prices:
    in: 1y
    class: GetTickerPricesJob
    enabled: false

  new_round:
    cron: '0 0 0 * * *'
    class: NewRoundJob

  liquidation:
    every: ['10s']
    class: LiquidationJob
