development:
  :concurrency: 5
  max_retries: 0
production:
  :concurrency: 20
:queues:
  - default

:schedule:
  end_game:
    cron: '0 0 0 * * *'
    class: EndGameJob

  get_tickers:
    in: 999y
    class: GetTickersJob
    enabled: false

  get_ticker_prices:
    in: 900y
    class: GetTickerPricesJob
    enabled: false

  new_round:
    cron: '0 0 0 * * *'
    class: NewRoundJob

  fight:
    in: 900y
    class: FightJob
    enabled: false

  destroy_fights:
    in: 900y
    class: DestroyFightsJob
    enabled: false
